### ISSUE TITLE
Support ruby 2.6.5

### ISSUE THREAD

**Issue by pjmartorell** [swipesense/ruby#8]
Hi! could you release new docker images with ruby 2.6.5? it solves a lot of security issues.
https://github.com/swipesense/ruby/blob/b742c85cdfdba1b2541c6937e6a1029d104d83d3/2.6/buster/slim/Dockerfile#L27

Thanks!

**Comment by jorihardman** [comment]
@pjmartorell thanks, this is building on dockerhub now!
